export * from "./Home";
export * from "./CheckoutPage";
export * from "./CatalogPage";
export * from "./NotFoundPage";
export * from "./SingleProductPage";
export * from "./AccountPage";
export * from "./SinglePostPage";
export * from "./ContactsPage";
export * from "./TrackOrderPage";
